<?php
//Seguridad
define("seguro",100);
define("inseguro",70);
define("muy_inseguro",50);
define("peligroso",30);
define("muy_peligroso",0);
//Salud
define("muy_saludable",100);
define("saludable",70);
define("no_saludable", 50);
define("perjudicial",30);
define("muy_perjudicial",0);
//Ambiente
define("muy_agradable",100);
define("agradable",70);
define("indiferente",50);
define("desagradable",30);
define("muy_desagradable",0);
